In [6]:
import numpy as np


In [4]:
# create the 1-D array
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [8]:
# two 2- D data
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# create 3 -D array
arr_3d = np.array([[[4,5,6],[7,8,9],[1,12,3]]])
arr_3d

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [ 1, 12,  3]]])

In [10]:
# create 4 -D data
arr_4d = np.array([[[[2,1,3],[6,5,4],[9,8,7]]]])
arr_4d

array([[[[2, 1, 3],
         [6, 5, 4],
         [9, 8, 7]]]])

In [13]:
#  1-D : Slice syntax:
#  arr[start:stop:step]


arr_1D = np.array([1,2,3,4,6,7])
print(arr_1D)
arr_1D[1:3]

[1 2 3 4 6 7]


array([2, 3])

In [18]:
arr_2d = np.array([[1,2,3,4],[4,5,7,8],[7,8,9,5]])
print(arr_2d)
arr_2d[1:,2:]

[[1 2 3 4]
 [4 5 7 8]
 [7 8 9 5]]


array([[7, 8],
       [9, 5]])

In [24]:
arr_3d = np.array([[[1,2,3,4],
                    [3,4,5,6],
                    [6,7,8,9],
                   [4,5,5,6]]])
print(arr_3d)
arr_3d[0,1:3,1:3]

[[[1 2 3 4]
  [3 4 5 6]
  [6 7 8 9]
  [4 5 5 6]]]


array([[4, 5],
       [7, 8]])

In [40]:
arr_4D = ([[[[1,2,3],
             [4,5,6],
             [7,8,9]],
          [[10,11,12],
           [13,14,15],
           [16,17,18]]]])
arr_4D

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
  [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]]

In [41]:
arr_4D[0,1,1:,1:]

TypeError: list indices must be integers or slices, not tuple

In [42]:
# check the dimension:
arr_2d.ndim

2

In [43]:
arr_3d.ndim

3

In [44]:
# array if zeros
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
# create the identity matrix:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
import numpy as np


# method(): range ():

In [3]:
# method(): range ():
arr_range = np.arange(2,15)
arr_range

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr_range = np.arange(2,15,2)
arr_range

array([ 2,  4,  6,  8, 10, 12, 14])

# create the line linspace :

In [7]:
# create the line linspace :
lin_space = np.linspace(0,1,5)
lin_space                     

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# random Array

In [8]:
# create the random array
array = np.random.rand(5,2)
array

array([[0.17943551, 0.38526295],
       [0.21396678, 0.52939821],
       [0.09888097, 0.74032834],
       [0.07688043, 0.06131514],
       [0.77300843, 0.12215564]])

# random integer Array

In [10]:
# create the random integer array:
array = np.random.randint(1,10,(4,4))
array

array([[9, 1, 1, 2],
       [5, 6, 9, 3],
       [1, 3, 2, 3],
       [5, 1, 3, 8]], dtype=int32)

In [12]:
# create the array:
array = np.array([[1,2,3,4],[2,3,4,5]])
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [13]:
# method 1 .shape():
array.shape

(2, 4)

In [14]:
# method 2 . check the dimention of array:
array.ndim

2

In [15]:
# method 3 : data type values
array.dtype

dtype('int64')

In [19]:
# method 4 : itemsize()
array.itemsize

8

In [20]:
array.nbytes

64

In [21]:
# Transpose the array:
array.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [22]:
array.shape

(2, 4)

In [23]:
# create the complex number
a = np.array([1+2j,3+4j])
a.real

array([1., 3.])

In [24]:
# create the complex number
a = np.array([1+2j,3+4j])
a.imag

array([2., 4.])

In [ ]:
# flat () :convert multi array into single array


In [25]:
array.sum(axis =0)

array([3, 5, 7, 9])

In [26]:
array.sum(axis =1)

array([10, 14])

In [29]:
# reshape():
a = np.array([1,2,3,4,5,6])
print(a)

print(a.reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [31]:
# sort()
age = np.random.rand(10,4)
np.sort(age)

array([[0.57710803, 0.81842936, 0.87737173, 0.96521518],
       [0.10328311, 0.23030421, 0.40366838, 0.90870762],
       [0.15103547, 0.28716942, 0.44513412, 0.96393374],
       [0.12105778, 0.42188   , 0.76457814, 0.85603452],
       [0.0781969 , 0.20412667, 0.4534871 , 0.77294171],
       [0.26032007, 0.27768137, 0.48264756, 0.96697141],
       [0.23973634, 0.36938438, 0.38492767, 0.63318282],
       [0.16969365, 0.26811394, 0.52127822, 0.6861689 ],
       [0.17866853, 0.416427  , 0.52135665, 0.86675596],
       [0.39990555, 0.45563245, 0.56696974, 0.96642374]])

In [33]:
import pandas as pd

In [48]:
name = ['Male','Female']
Gender = np.random.choice(name,50)
Gender

array(['Female', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Male',
       'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Female', 'Male', 'Female'],
      dtype='<U6')

In [37]:
# generate the float value
Salary = np.random.uniform(10000,25000,100)
Salary

array([21736.65288996, 18866.11980086, 18602.9248917 , 11258.97528939,
       16652.99807042, 16924.62985745, 15966.10542337, 20889.7304402 ,
       17943.73856582, 22689.18067424, 20492.2523934 , 22459.0127613 ,
       21615.94804224, 21477.51175823, 10073.13391128, 10974.13105916,
       18403.66733424, 13539.91416521, 12739.99841952, 19039.41834644,
       12749.65689225, 19743.08261074, 10134.92775512, 10431.8532494 ,
       11907.25084732, 13583.05181685, 12381.18320411, 21500.40902515,
       18401.563846  , 10394.93319543, 16233.24597474, 22316.97510323,
       22013.95680278, 17242.06570944, 15362.58640806, 17159.78895394,
       15214.72295881, 18233.07646672, 12023.80714731, 15367.78269141,
       22371.64889265, 19008.74204997, 20211.8453265 , 16808.04197114,
       11106.84672333, 18739.97715842, 16183.18667266, 11833.35859034,
       12524.98170151, 10389.73131919, 14604.03389867, 11300.96487399,
       21157.31777607, 12362.52684612, 12054.32855841, 16392.61801618,
      

In [40]:
Salary = np.random.uniform(10000,25000,100)
np.round(Salary,2)

array([22573.97, 20854.16, 10190.71, 15915.23, 22110.47, 20834.84,
       10607.01, 24261.46, 12510.12, 16901.1 , 22000.02, 22921.22,
       10733.15, 15131.97, 21128.85, 22166.45, 18641.15, 21379.8 ,
       22996.89, 18192.72, 22944.64, 11758.26, 12008.65, 18495.9 ,
       16975.68, 12039.97, 22557.02, 24770.43, 11288.38, 22767.41,
       16390.69, 23523.88, 18859.79, 18734.97, 24882.56, 16727.96,
       22630.12, 15024.62, 22613.24, 19968.15, 17083.66, 16241.89,
       22935.68, 12894.41, 13554.88, 16020.94, 21183.65, 22759.5 ,
       21881.4 , 24787.61, 13681.42, 23452.18, 10737.12, 10867.68,
       14770.83, 13298.07, 24611.52, 15265.83, 17224.75, 21125.32,
       19605.61, 11688.96, 21259.92, 10777.87, 12423.94, 18358.56,
       14110.4 , 21826.69, 23993.44, 12957.34, 15364.46, 21524.62,
       21480.  , 11975.99, 22066.04, 14234.43, 14190.05, 13502.55,
       20074.91, 23863.91, 21547.56, 12208.81, 16973.23, 19560.39,
       17098.31, 19564.44, 16974.7 , 23598.51, 17759.91, 19494

In [ ]:
Age = np.

In [ ]:
# id : 100
# Name 
# Gender
# Dept
# Exp
# Role
# Salary

In [41]:
import pandas as pd
df = pd

In [55]:
ID = np.arange(100,201)

name = ["santosh","sagar","paritosh","ganesh","ramesh","suresh","dinesh","gukesh",]
Name = np.random.choice(name,100)
print(name)
gender = ['Male',"Female"]
Gender = np.random.choice(gender,10)
print(gender)

dept = ["IT","HR","Finance","Ele","Civil"]
Dept = np.random.choice(dept,25)
print(dept)

exp = np.random.uniform(1,20,50)
exp = np.round(exp,1)
print(exp)

['santosh', 'sagar', 'paritosh', 'ganesh', 'ramesh', 'suresh', 'dinesh', 'gukesh']
['Male', 'Female']
['IT', 'HR', 'Finance', 'Ele', 'Civil']
[ 5.4 13.6  1.5 18.3 12.5 17.  13.   3.9 12.1 18.8  4.8 18.  17.6 16.5
  3.7  9.1 17.8 18.   3.7 10.8 13.9 11.7 17.1  2.8 14.6 18.1 15.5  8.3
  1.5  7.1 18.7 18.   6.2 15.4  1.3  8.9  2.7  8.6  9.   9.3  9.3 15.9
 13.4 10.9 13.6  5.4  5.4 18.6  1.2 13.7]


In [57]:
role = ["Ai","Data science","Testing","Devops","Devloper"]
role.np.random.choice(role,100)
role

AttributeError: 'list' object has no attribute 'pd'

In [50]:
salary = np.random.choice(45000,100000,100)
salary = np.round(salary,100)
salary

array([13185, 25994, 18323, ...,  6361, 24809, 18903],
      shape=(100000,), dtype=int32)

In [ ]:
import pandas as pd
df = pd.DataFrame({
            "ID":Id
})